version: "3.5"
services:
  lrn:
    build: .
    ports:
      - 5000:5000
    working_dir: /var/www/subd_project
    command: "air -c .air.toml"
    volumes:
      - ../:/var/www/subd_project
      - ./.air.toml:/var/www/subd_project/.air.toml:rw
    environment:
      - DB_HOST=db
      - POSTGRES_USER=subd_project
      - POSTGRES_PASSWORD=123azxv
      - POSTGRES_DB=technopark
    depends_on:
      - db

  db:
    image: postgres
    container_name: "project-db"
    ports:
      - 5432:5432
    volumes:
      - ../../db_dump:/tmp
    environment:
      - POSTGRES_USER=subd_project
      - POSTGRES_PASSWORD=123azxv
      - POSTGRES_DB=technopark